### ISSUE TITLE
The libvorbis ebuild is not multilib compatible

### ISSUE THREAD

**Issue by gabrielesvelto** [rindeal/rindeal-ebuild-repo#190]
I'm on a multilib x86-64 system with the `media-libs/libvorbis abi_x86_32` flag in `/etc/portage/package.use`. emerge refuses to update the package using the rindeal ebuild because it does not support multilib dependencies.

**Comment by rindeal** [comment]
Yes, my repo doesn't contain any multilib support, so if this package in particular is messing with your emerge routine, the simplest way is probably to put `media-libs/libvorbis::rindeal` to your `{sysconfigdir}/portage/package.mask...`.

**Comment by gabrielesvelto** [comment]
OK, thanks. Would you accept a contribution for multilib support on this package alone?

**Comment by rindeal** [comment]
No, but if you want my ebuild for this software so much (instead of the Gentoo one), you can always fork it to your own repo, add your own multilib support on top and it should work just fine. This software also sees new releases quite rarely so further maintenance shouldn't be too bad.

**Comment by gabrielesvelto** [comment]
Alright, thanks.
