### ISSUE TITLE
pycurl IUSE-related emerge fail

### ISSUE THREAD

**Issue by gh2k** [rindeal/rindeal-ebuild-repo#226]
pycurl is complaining that 'doc' is not in IUSE during src_install:
```
 * python3_5: running distutils-r1_run_phase python_install_all
 * ERROR: dev-python/pycurl-7.43.0.1::rindeal failed (install phase):
 *   USE Flag 'doc' not in IUSE for dev-python/pycurl-7.43.0.1
 * 
 * Call stack:
 *          ebuild.sh, line  124:  Called src_install
 *        environment, line 3031:  Called distutils-r1_src_install
 *        environment, line 1078:  Called _distutils-r1_run_common_phase 'python_install_all'
 *        environment, line  417:  Called multibuild_foreach_variant 'distutils-r1_run_phase' 'python_install_all'
 *        environment, line 1934:  Called _multibuild_run 'distutils-r1_run_phase' 'python_install_all'
 *        environment, line 1932:  Called distutils-r1_run_phase 'python_install_all'
 *        environment, line 1042:  Called python_install_all
 *        environment, line 2730:  Called use 'doc'
 *   phase-helpers.sh, line  201:  Called die
 * The specific snippet of code:
 *   				die "USE Flag '${u}' not in IUSE for ${CATEGORY}/${PF}"
 * 
```

It's listed in IUSE_A in the variable, but I'm not sure how this makes its way into IUSE. It's been a while since I wrote an ebuild.

Copying the ebuild to my local overlay and adding changing IUSE_A=(doc and friends) to IUSE="doc and friends" works, but I'm not sure that this is the *best* fix so I haven't made a PR.

I'm running portage 2.3.19 if that helps. It seems like a straightforward error so I haven't attached any big logs, but let me know if you need them.

**Comment by rindeal** [comment]
yeah, yeah, I know, I fixed it in my dev branch 10 days ago, but haven't merged it yet, because I've got busy with other things. Sorry.

**Comment by rindeal** [comment]
Sorry it took so long, the whole infrastructure I'm using to build and test packages is now going through a major revamp. There will be some modularization, containerization and a lot of automation, but hopefully it will bring the overall package quality to new highs. Cheers.

**Comment by gh2k** [comment]
Thanks! :-)
