### ISSUE TITLE
Uzbl fails on musl

### ISSUE THREAD

**Issue by FrozenPigs** [rindeal/rindeal-ebuild-repo#229]
I tried building you're uzbl-9999 ebuild using paludis on my musl install but it fails with this error:
<pre>
>>> Running ebuild phase killold as root:root...
>>> Starting builtin_killold
>>> Done builtin_killold
>>> Completed ebuild phase killold
>>> Running ebuild phases init saveenv as paludisbuild:paludisbuild...
>>> Starting builtin_init
>>> Done builtin_init
die trap: exiting with error.
</pre>
After taking a peak at the ebuild I saw that glib was a requirement, so I assumed that may be it, do you have any ideas?

**Comment by rindeal** [comment]
Have you tried building it with portage?

**Comment by FrozenPigs** [comment]
Just did that, got this `/bin/sh: pip3: command not found`, I'll install that and see what happens, my bad heh.

**Comment by FrozenPigs** [comment]
Now it gives me this https://paste.pound-python.org/show/Wg4sGcDdD7m07vbKgfAl/

**Comment by rindeal** [comment]
I have reverted the upstream commit that caused this mess + I've updated some things here and there so it builds now on my machine. I was unable to make it run though, but that's probably because upstream development is alpha quality and currently stale.

**Comment by FrozenPigs** [comment]
Well that got it to install on my other gentoo install but not my original one, but even on the install I got it on it didn't work heh, just got a blank screen. So far it seems like my musl install is going to be hopeless with browsers anyway, surf wont work, uzbl wont install, and firefox wont even launch, this install and me are going through some hard times.
