### ISSUE TITLE
 [media-libs/vulkan-sdk-1.1.73.0] VkLayer_parameter_validation

### ISSUE THREAD

**Issue by EinstokFair** [rindeal/rindeal-ebuild-repo#235]
<a href="https://gist.github.com/EinstokFair/5fb61c3e39e0e045657d8ef9732d9bd2">build.log</a>

**Comment by rindeal** [comment]
This looks like an issue with GCC5, which is deprectaed in Gentoo. Try to build with GCC6 and if issue persists, open a new request.
