### ISSUE TITLE
[req] dev-util/amd-app-sdk-3.0.130

### ISSUE THREAD

**Issue by EinstokFair** [rindeal/rindeal-ebuild-repo#237]
https://gpo.zugaina.org/dev-util/amd-app-sdk

what do you think about packaging this software? Is any new SDK replaced it in 2018 (more than 2 years passed from the last release of AMD APP SDK, is it <a href="https://developer.amd.com/amd-open64-software-development-kit/">Open64 SDK</a>)?

I need it becase of "bufferbandwidth" utility to measure PCIe transfer rate to videocard.

Thanks.

**Comment by rindeal** [comment]
[BufferBandwidth.zip](https://github.com/rindeal/rindeal-ebuild-repo/files/1958303/BufferBandwidth.zip)

does this work for you?

**Comment by EinstokFair** [comment]
It looks like binary file in zip archive. I don't run binaries, I use gentoo to build software from sources...

**Comment by rindeal** [comment]
AMD APP SDK is a proprietary software full of binaries. The zipped file is the "The pre-
compiled  sample  executable" as mentioned in the docs.

**Comment by rindeal** [comment]
If you want just this tiny part of this huge blob then it doesn't make sense to package it. Just extract all the needed source code and compile it yourself if you don't want to use the pr-compiled binary.

**Comment by EinstokFair** [comment]
I think that I have no enough skills for that. Does it require some libraries from that SDK? Or it can be compiled with opensource software only?

**Comment by rindeal** [comment]
well, then what's the pre-compiled binaries are for...

**Comment by ArsenShnurkov** [comment]
The .ebuild files are for this. Trusted recipe and automation script in one thing.
Pre-compiled binaries are for injection of malicious software into a system.
