### ISSUE TITLE
net-misc/curl-7.60.0 USE flags require revision?

### ISSUE THREAD

**Issue by prototype99** [rindeal/rindeal-ebuild-repo#240]
my system has a system wide threads use flag, when attempting to emerge I got this:
`The following REQUIRED_USE flag constraints are unsatisfied:
    threads? ( dns_threaded )`
so presumably enabling threads should imply the dns_threaded use flag? also, it conflicts with net-misc/megasync-3.6.5-r1::ssnb as it doesn't have the use flag "curl_ssl_openssl", perhaps ssl_openssl should be renamed to match the official tree? (to help ensure better compatibility).  i can see upon further examination that you do in fact have a convention that this will break, would it be better to suggest to the ssnb overlay that they code in an either/or dependency? (even though there could be other ebuilds that also clash with this) it's your choice after all either way. (neat git-hosting eclass btw)

**Comment by rindeal** [comment]
There is something fishy going on with those threads in my ebuild indeed, I'll have to look into it.

As for those SSL USE-flags:

```sh
IUSE_A=(
    ...
    curl_ssl_openssl curl_ssl_...
)
REQUIRED_USE_A=(
    ...
    "curl_ssl_openssl? ( ssl_openssl ) !curl_ssl_openssl? ( !ssl_openssl )"
)
```

should get the job done.

**Comment by prototype99** [comment]
ohhhh i get it, so basically we have an empty use flag to serve as an alias/wrapper for the real one? it's 22:14 here so i will rest for now, but if it's not finished when i wake up i'll make a pull request for that to help speed things up a lil. i'll change it to an -r1 suffix though because i guess it would technically be classed as a revision/patch?

**Comment by rindeal** [comment]
> ohhhh i get it, so basically we have an empty use flag to serve as an alias/wrapper for the real one?

more like a dummy which pulls the proper required USE-flag, since proper USE-flag aliases do not exist (as a feature).

And no, such a change doesn't warrant a revision bump, because for those who need the new USE-flags a simple repo sync will be enough for Portage to know it should rebuild curl to have the new USE-flags in. And it won't be unnecessarily rebuilt for those who don't need them. Revbumps are for mainly for bugfixes.

**Comment by prototype99** [comment]
oh okay i always thought that included bugs in the actual ebuild, fair enough.

**Comment by prototype99** [comment]
pull request is up, let me know if it needs any tweaking

**Comment by prototype99** [comment]
not quite sure what's up now, it appears (?) to clash with the pycurl ebuild now. I masked it so it would be forced to use the official version and the dependencies were fixed.
[terminal.txt](https://github.com/rindeal/rindeal-ebuild-repo/files/2174197/terminal.txt)

**Comment by rindeal** [comment]
I've updated the pycurl ebuild, try now.

**Comment by prototype99** [comment]
definitely a different issue now, however now pycurl does not want to emerge 
[terminal.txt](https://github.com/rindeal/rindeal-ebuild-repo/files/2184103/terminal.txt)

**Comment by rindeal** [comment]
pycurl's `ssl_openssl` flag is enabled by default, you must have disabled it somewhere in your config files.

**Comment by prototype99** [comment]
oh okay my bad! had an old automatic package.use entry from when there were issues, emerged beautifully now.
