### ISSUE TITLE
missing masters=gentoo

### ISSUE THREAD

**Issue by samuelbernardo** [rindeal/rindeal-ebuild-repo#242]
When synchronizing the repository for the first time it appears the following warining about missing atribute:
```
!!! Repository 'rindeal' is missing masters attribute in '/var/db/repos/rindeal/metadata/layout.conf'
!!! Set 'masters = gentoo' in this file for future compatibility
* In post-repository hook for rindeal
** synced from remote repository https://ebuilds.janchren.eu/repos/rindeal/.git
** synced into /var/db/repos/rindeal
```

**Comment by rindeal** [comment]
This cryptic message actually means that your sync failed and you downloaded about zero bytes of actual content. Is my guess correct?

**Comment by samuelbernardo** [comment]
Hi @rindeal 
No. It synced correctly, but I noticed that after eix-sync finished it appeared '/var/db/repos/rindeal/metadata/layout.conf' with masters=gentoo. I didn't create the directory for the overlay and it was created successfully by eix-sync.
So since layout.conf is correctly configured, maybe the problem is with eix-sync scripts order, but I never realize this problem before.
After the first sync it's working correctly.

**Comment by rindeal** [comment]
So you did at least two syncs and now it's working?

**Comment by samuelbernardo** [comment]
yes. After the first sync it works correctly.
