### ISSUE TITLE
Validity Sensor ebuild broken

### ISSUE THREAD

**Issue by dpowers86** [rindeal/rindeal-ebuild-repo#245]
The validity-sensor is broken (validity-sensor-4.5.118.00-r1.ebuild). The URL does not point to a valid file "ftp://ftp.hp.com/pub/softpaq/sp62001-62500/sp62413.tar". Is there another place we can grab this file from?

**Comment by rindeal** [comment]
There is a new upstream version and the ebuild is a bit outdated. I'll close this issue in favour of https://github.com/rindeal/rindeal-ebuild-repo/issues/216.
