### ISSUE TITLE
dev-util/smartgit-19.1.1 Not Found

### ISSUE THREAD

**Issue by Progman3K** [rindeal/rindeal-ebuild-repo#248]
Hello,

I'm trying to install smartgit from the rindeal overlay and it errors out like this:

>>> Emerging (1 of 1) dev-util/smartgit-19.1.1::rindeal
>>> Downloading 'https://file.io/zqSrfh'
--2019-08-23 10:00:29--  https://file.io/zqSrfh
Resolving file.io... 35.174.199.61, 52.45.188.161
Connecting to file.io|35.174.199.61|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2019-08-23 10:00:29 ERROR 404: Not Found.

!!! Couldn't download 'smartgit-19.1.1.tar.gz'. Aborting.
 * Fetch failed for 'dev-util/smartgit-19.1.1', Log file:
 *  '/var/tmp/portage/dev-util/smartgit-19.1.1/temp/build.log'

**Comment by rindeal** [comment]
You're right, the file hosting provider deleted the file apparently, I'll have to find another.
