### ISSUE TITLE
No egg-info in installed PySide2.

### ISSUE THREAD

**Issue by alexey001** [rindeal/rindeal-ebuild-repo#250]
Pyside2 package installed without egg metainfo. It causes problems with packages using pkg_resources. Unfortunately, I have no idea how to implement this correctly :(

**Comment by rindeal** [comment]
My repository doesn't provide and never has provided PySide2 package.

**Comment by alexey001** [comment]
Ohh. Sorry , I made a mistake with the browser window :)
